name = "adventure-log"
compatibility_date = "2025-06-20"

main = ".svelte-kit/cloudflare/_worker.js"

compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[assets]
directory = ".svelte-kit/output/client"
binding = "ASSETS"

[site]
bucket = ".svelte-kit/output/client"
